###############################################################################
#                          Generated on docker.io                          #
###############################################################################
version: "3.1"
services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: goteo-mailhog
    logging:
      driver: none
    ports:
      - "8082:8025"
      - "1025:1025"

  mariadb:
    image: mariadb:10.2
    container_name: goteo-mariadb
    working_dir: /application
    volumes:
      - .:/application
      - goteo-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=crowdfunding
      - MYSQL_DATABASE=goteo
      - MYSQL_USER=goteo
      - MYSQL_PASSWORD=goteo
    ports:
      - "3307:3306"

  webserver:
    image: nginx:alpine
    container_name: goteo-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
      - "8443:443"
      - "35729:35729"

  geoip:
    image: igortimoshenko/docker-maxmind-geoip
    container_name: goteo-geoip
    volumes:
      - goteo-geoip:/usr/share/GeoIP

  php:
    build: docker/php
    container_name: goteo-php
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - goteo-geoip:/usr/share/GeoIP
    environment:
      - GOTEO_CONFIG_FILE
      - DEBUG
      - UID
    command: ./docker/php/init.sh

volumes:
  goteo-mariadb:
  goteo-geoip:
