CREATE TABLE `node_data` (
`node` VARCHAR( 50 ) NOT NULL ,
`projects` SMALLINT UNSIGNED NULL DEFAULT '0',
`active` TINYINT UNSIGNED NULL DEFAULT '0',
`success` SMALLINT UNSIGNED NULL DEFAULT '0',
`investors` SMALLINT UNSIGNED NULL DEFAULT '0',
`supporters` SMALLINT UNSIGNED NULL DEFAULT '0',
`amount` MEDIUMINT UNSIGNED NULL DEFAULT '0',
`budget` MEDIUMINT UNSIGNED NULL DEFAULT '0',
`rest` MEDIUMINT UNSIGNED NULL DEFAULT '0',
`calls` TINYINT UNSIGNED NULL DEFAULT '0',
`campaigns` TINYINT UNSIGNED NULL DEFAULT '0',
`updated` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY ( `node` )
) ENGINE = InnoDB COMMENT = 'Datos resumen nodo';
