<?php
/*
 * This file is part of the Goteo Package.
 *
 * (c) Platoniq y Fundación Goteo <fundacion@goteo.org>
 *
 * For the full copyright and license information, please view the README.md
 * and LICENSE files that was distributed with this source code.
 */

namespace Goteo\Application\Config;

use Goteo\Application\App;
use Symfony\Component\Config\ConfigCache;
use Symfony\Component\Config\Loader\FileLoader;
use Symfony\Component\Yaml\Yaml;

class YamlSettingsLoader extends FileLoader
{
    static public $cached_files = [];

    static public function getCacheFilename($resource): string
    {
        return GOTEO_CACHE_PATH . 'config/' . md5($resource) . '.php';
    }

    static public function getConfigCache($file): ConfigCache
    {
        // the second argument indicates whether or not you want to use debug mode
        return new ConfigCache($file, App::debug());
    }

    public function load($resource, $type = null)
    {
        $cachePath = static::getCacheFilename($resource);
        static::$cached_files[] = $cachePath;
        $cacheMatcher = static::getConfigCache($cachePath);

        if (!$cacheMatcher->isFresh()) {
            $config = Yaml::parse(file_get_contents($resource));
            $code = $this->exportPhpArrayAsString($config);
            $cacheMatcher->write($code);
        }

        // you may want to require the cached code:
        return require $cachePath;
    }

    public function supports($resource, $type = null): bool
    {
        return is_string($resource) && 'yml' === pathinfo(
            $resource,
            PATHINFO_EXTENSION
        );
    }

    /**
     * @param $config
     * @return string
     */
    private function exportPhpArrayAsString($config): string
    {
        $code = "<?php\n" .
            "// auto-generated by %s\n" .
            "// date: %s\nreturn %s;\n";
        return sprintf(
            $code,
            __CLASS__,
            date('Y/m/d H:i:s'),
            var_export($config, true)
        );
    }
}
