INSERT INTO `template` VALUES(41, 'Difunde, difunde, difunde', 'tips', 'Mensaje al impulsor a partir del primer día de campaña', 'Difunde, difunde, difunde tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(42, 'Comienza por lo más próximo', 'tips', 'Mensaje al impulsor a partir del segundo día de campaña', 'Comienza por lo más próximo a tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(43, 'Una acción a diario, por pequeña que sea', 'tips', 'Mensaje al impulsor a partir del tercer día de campaña', ' Una acción a diario, por pequeña que sea, sobre tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(44, 'Llama a todas las puertas', 'tips', 'Mensaje al impulsor a partir del cuarto día de campaña', ' Llama a todas las puertas, es tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(45, 'Busca dónde está tu comunidad', 'tips', 'Mensaje al impulsor a partir del quinto día de campaña', 'Busca dónde está tu comunidad y la encontrarás. Es tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(46, 'Apóyate en quienes te van apoyando', 'tips', 'Mensaje al impulsor a partir del séptimo día de campaña y si tiene más de 20 cofinanciadores', 'Apóyate en quienes te van apoyando, es tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(47, 'Agradece en público e individualmente', 'tips', 'Mensaje al impulsor a partir del octavo día de campaña', 'Agradece en público e individualmente, es tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(48, 'Busca prescriptores e implícalos', 'tips', 'Mensaje al impulsor a partir del noveno día si no tiene padrinos', 'Busca prescriptores e implícalos en tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(49, 'Luce tus recompensas y retornos', 'tips', 'Mensaje al impulsor a partir del décimo día de campaña', 'Luce tus recompensas y retornos de tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(50, 'Refresca tu mensaje de motivacion', 'tips', 'Mensaje al impulsor a partir del decimoprimer día de campaña si no tiene video motivacional', 'Refresca tu mensaje de motivacion en tu proyecto %PROJECTNAME%', 'Hola...');
INSERT INTO `template` VALUES(51, 'Sigue los avances y calcula lo que falta', 'tips', 'Mensaje al impulsor a partir del decimoquito día de campaña si no ha llegado al mínimo', 'Sigue los avances y calcula lo que falta a tu proyecto %PROJECTNAME%', 'Hola...');

INSERT INTO `template` VALUES(65, 'Agradecimiento recarga monedero', 'invest', 'Mensaje al usuario al recargar su monedero', 'Muchas gracias por recargar tu monedero!', 'Hola %USERNAME%! <p>Tu monedero acaba de ser recargado con %AMOUNT_RECHARGUED%.</p><p>En este momento dispones de un total de %AMOUNT_RECHARGUED% en <a href="%WALLET_URL%">tu monedero</a> para invertir en proyectos de Goteo.</p><p>Te recordamos que la recarga de crédito otorga la posibilidad de <a href="%CERTIFICATE_URL%">descargar un certificado de desgravación fiscal</a></p>');

INSERT INTO `template` VALUES(66, 'Aviso proyecto favorito', 'invest', 'Mensaje al usuario recordando proyecto favorito', 'Te recordamos que la campaña %PROJECTNAME% esta a punto de terminar', 'Hola %USERNAME%! <p>Te recordamos que a la campaña <a href="%PROJECTURL%">%PROJECTNAME%</a> le quedan %DAYS_LEFT% días y %MONEY_LEFT% para alcanzar su presupuesto mínimo y necesita tu ayuda para conseguirlo.</p><p>Gota a gota… ¡el río suena! :)</p><p>El equipo de Goteo</p>');

-- actualizacion textos
UPDATE `template` SET `text` = '<p>Hola %USERNAME%!</p>\r\n\r\n<p>Muchas gracias por tu interés en Goteo, tu cuenta ha sido creada con éxito :)</p>\r\n<p>Para confirmar tu dirección de correo electrónico y completar el registro, haz clic en el siguiente enlace (o cópialo en la barra de dirección del navegador):</p>\r\n\r\n<p><span class=\"message-highlight-blue\"><a href=\"%ACTIVATEURL%\">%ACTIVATEURL%</a></span></p>\r\n\r\n<p>Te invitamos a apoyar esta apuesta por el crowdfunding abierto cofinanciando, dentro de tus posibilidades, alguna de las iniciativas que encontrarás destacadas en la portada de <a href=http://goteo.org/">http://goteo.org/</a> cuando accedas. Ayudarás así a hacer realidad los fantásticos retornos colectivos que proponen.</p>\r\n\r\n<p>Saludos!</p>\r\n\r\n<p>The Goteo Mailer<br>\r\n<a href=http://goteo.org/">http://goteo.org/</a><br>\r\nFinanciación colectiva con ADN abierto<br>\r\nCrowdfunding the Commons<br>\r\n- - - - - - - - - - - - - - - - - - - -<br>\r\ninfo@goteo.org<br>\r\ntwitter/identi.ca: @goteofunding</p> ' WHERE `id` = '5';

UPDATE `template_lang` SET `text` = '<p>Hola %USERNAME%!</p>\r\n\r\n<p>Moltes gràcies pel teu interès per Goteo, el teu compte ha estat creat amb èxit :)</p>\r\n<p>Per confirmar la teva adreça de correu electrònic i completar el registre, fes clic al següent enllaç (o copia\'l a la barra del navegador):</p>\r\n\r\n<p><span class=\"message-highlight-blue\"><a href=\"%ACTIVATEURL%\">%ACTIVATEURL%</a></span></p>\r\n\r\n<p>Et convidem a recolzar aquesta aposta pel crowdfunding obert cofinançant, dins de les teves possibilitats, alguna de les iniciatives que trobaràs destacades a la nostra portada (https://goteo.org/). Ajudaràs així a fer realitat els fantàstics retorns col·lectius que proposen.</p>\r\n<p>Salutacions!</p>\r\n\r\n<p>\r\nThe Goteo Mailer<br>\r\n<a href=http://goteo.org/">http://goteo.org/</a><br>\r\nFinançament col.lectiu amb ADN obert<br>\r\nCrowdfunding the Commons<br>\r\n- - - - - - - - - - - - - - - - - - - -<br>\r\ninfo@goteo.org<br>\r\ntwitter/identi.ca: @goteofunding</p> ' WHERE `id` = '5' AND `lang` = 'ca';

UPDATE `template_lang` SET `text` = '\r\n\r\n\r\n<p>Dear %USERNAME%!</p>\r\n\r\n<p>Thank you very much for your interest in Goteo. Your account has been successfully created :)</p>\r\n<p>In order to confirm your email address and complete the registration, please click on the following link (or copy it to your browser\'s address bar):</p>\r\n\r\n<p><span class=\"message-highlight-blue\"><a href=\"%ACTIVATEURL%\">%ACTIVATEURL%</a></span></p>\r\n\r\n<p>We invite you to support this effort toward open, co-financed crowdfunding as much as your circumstances permit, perhaps through one of the proposals that you\'ll find highlighted on the front page of <a href=http://goteo.org/">http://goteo.org/</a> when you log in. In that way, you\'ll help make real the fantastic collective returns that are proposed.</p>\r\n<p>Cheers,</p>\r\n\r\n<p>The Goteo Mailer <br>\r\n<a href=http://goteo.org/">http://goteo.org/</a><br>\r\nCollective financing with open DNA<br>\r\nCrowdfunding the Commons<br>\r\n- - - - - - - - - - - - - - - - - - - -<br>\r\nhola@goteo.org<br>\r\ntwitter/identi.ca: @goteofunding</p>\r\n' WHERE `id` = '5' AND `lang` = 'en';

UPDATE `template_lang` SET `text` = '\r\n\r\n\r\n<p>Kaixo %USERNAME%!</p>\r\n\r\n<p>Eskerrik asko Goteo dela-eta daukazun interesarengatik. Zure kontua arrakastaz sortu da :)</p>\r\n<p>Zure posta elektronikoko helbidea baieztatzeko eta erregistroa osatzeko, egin klik hurrengo estekan (edo kopia ezazu nabigatzaileko helbide-barran):</p>\r\n\r\n<p><span class=\"message-highlight-blue\"><a href=\"%ACTIVATEURL%\">%ACTIVATEURL%</a></span></p>\r\n\r\n<p>Gonbita egiten dizugu cowdfunding irekiaren aldeko apustu hau babes dezazun, zure ahalbideekin <a href=http://goteo.org/">http://goteo.org/</a>-en azalean aurkituko dituzun ekimenetako bat kofinantziatuz. Horrela, proposatzen diren itzulera kolektibo miragarriak egia bihurtuko dituzu.</p>\r\n<p>Agur!</p>\r\n\r\n<p>\r\nThe Goteo Mailer<br>\r\n<a href=http://goteo.org/">http://goteo.org/</a><br>\r\nDNA irekia duen finantzaketa kolektiboa<br>\r\nCrowdfunding the Commons<br>\r\n- - - - - - - - - - - - - - - - - - - -<br>\r\nhola@goteo.org<br>\r\ntwitter/identi.ca: @goteofunding</p>\r\n' WHERE `id` = '5' AND `lang` = 'eu';

UPDATE `template_lang` SET `text` = '<p>Bonjour %USERNAME%!</p>\r\n\r\n<p>Votre compte a été créé avec un succès. Merci beaucoup pour l\'intérêt que vous portez à Goteo</p>\r\n<p>Pour confirmer votre inscription, regardez le lien envoyé par mail (ou copiez l\'adresse dans la barre de votre navigateur):</p>\r\n\r\n<p><span class=\"message-highlight-blue\"><a href=\"%ACTIVATEURL%\">%ACTIVATEURL%</a></span></p>\r\n\r\n<p>A bientôt</p>\r\n\r\n<p>The Goteo Mailer<br>\r\n<a href=http://goteo.org/">http://goteo.org/</a><br>\r\nFinancement collectif de projets ouverts et libres<br>\r\nCrowdfunding the Commons<br>\r\n- - - - - - - - - - - - - - - - - - - -<br>\r\nhola@goteo.org<br>\r\ntwitter/identi.ca: @goteofunding</p> ' WHERE `id` = '5' AND `lang` = 'fr';
