#!/bin/sh
DIR=$(dirname $(dirname $(readlink -f $0)))

if [ -z "$GOTEO_TEST_CONFIG_FILE" ]; then
    if [ -f "./config/test-docker-settings.yml" ]; then
        GOTEO_TEST_CONFIG_FILE="./config/test-docker-settings.yml"
    else
        GOTEO_TEST_CONFIG_FILE="./config/local-docker-settings.yml"
        echo
        echo "\e[31mWarning:\e[0m Using $GOTEO_TEST_CONFIG_FILE for testing"
        echo "You might want to create a proper \e[32mtest-docker-settings.yml\e[0m file"
        echo
    fi
fi
$DIR/docker/exec ./run-tests.sh -t $GOTEO_TEST_CONFIG_FILE "$@"
