#!/bin/sh
if [[ "$OSTYPE" =~ ^linux ]]; then
	export UID=`id -u`
fi

DOCKER_FILE=
if [ -f "docker-compose-local.yml" ]; then
	DOCKER_FILE='-f docker-compose-local.yml'
fi

docker-compose $DOCKER_FILE up $@
