CREATE TABLE `feed` (
`id` SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`title` TINYTEXT NOT NULL ,
`url` TINYTEXT DEFAULT NULL ,
`datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`scope` VARCHAR( 50 ) NOT NULL ,
`type` VARCHAR( 50 ) NOT NULL ,
`html` TEXT NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Log de eventos';

-- alters
ALTER TABLE `feed` CHANGE `url` `url` TINYTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `feed` ADD `image` INT( 10 ) NULL ;