CREATE TABLE  `comment` (
`id` SERIAL NOT NULL ,
`post` BIGINT UNSIGNED NOT NULL ,
`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`text` TEXT NOT NULL ,
`user` VARCHAR( 50 ) NOT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT =  'Comentarios';