<?php
/*
 * This file is part of the Goteo Package.
 *
 * (c) Platoniq y Fundación Goteo <fundacion@goteo.org>
 *
 * For the full copyright and license information, please view the README.md
 * and LICENSE files that was distributed with this source code.
 */

namespace Goteo\Console;

use Goteo\Application\App;
use Goteo\Application\Config;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\EventDispatcher\Event;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class Console {
    static protected $app;
	static protected $console;
	static protected array $commands = [];

	/**
	 * Creates a new instance of the App ready to run
	 * Next calls to this method will return the current instantiated App
	 * @return Application object
	 */
	static public function get() {
		if (!self::$console) {
			// Old constants compatibility generated by the dispatcher
			$url = Config::get('url.main');
			define('SITE_URL', (Config::get('ssl')?'https://':'http://').preg_replace('|^(https?:)?//|i', '', $url));

			self::$app = App::getService('console');
            self::$console = new Application();
            /** @var EventDispatcherInterface $dispatcher */
            $dispatcher = App::getService('dispatcher');
            self::$console->setDispatcher($dispatcher);

			foreach (self::$commands as $command) {
				self::$console->add($command);
			}
		}

		return self::$console;
	}

	static public function add(Command $command) {
		self::$commands[] = $command;
		if (self::$console) {
			self::$console->add($command);
		}
	}

	static public function dispatch(string $eventName, Event $event = null): Event
    {
		return self::$app->getDispatcher()->dispatch($event, $eventName);
	}

	/**
	 * Enables debug mode witch does:
	 * - *.yml settings always read
	 * - A bottom html profiler tool will be displayed on the bottom of the page
	 * - SQL queries will be collected fo statistics
	 * - Html/php error will be shown
	 */
	static public function debug(bool $enable = null): bool
    {
		return App::debug($enable);
	}

}
