INSERT INTO `text` VALUES ('step-1', 'es', 'PERFIL');
INSERT INTO `text` VALUES ('step-2', 'es', 'DATOS PERSONALES');
INSERT INTO `text` VALUES ('step-3', 'es', 'DESCRIPCIÓN');
INSERT INTO `text` VALUES ('step-4', 'es', 'COSTES');
INSERT INTO `text` VALUES ('step-5', 'es', 'RETORNO');
INSERT INTO `text` VALUES ('step-6', 'es', 'COLABORACIONES');
INSERT INTO `text` VALUES ('step-7', 'es', 'PREVISUALIZACIÓN');

INSERT INTO `text` VALUES ('regular-mandatory', 'es', 'Campo obligatorio!');
INSERT INTO `text` VALUES ('explain-project-progress', 'es', 'Texto bajo el título Estado global de la información');

INSERT INTO `text` VALUES ('guide-user-register', 'es', 'Texto guía en el registro de un nuevo usuario.');
INSERT INTO `text` VALUES ('guide-user-data', 'es', 'Texto guía en la edición de campos sensibles.');
INSERT INTO `text` VALUES ('guide-user-information', 'es', 'Texto guía en la edición de información del usuario.');
INSERT INTO `text` VALUES ('guide-project-user-information', 'es', 'Texto guía en el paso PERFIL del formulario de proyecto.');
INSERT INTO `text` VALUES ('guide-project-contract-information', 'es', 'Texto guía en el paso DATOS PERSONALES del formulario de proyecto.');
INSERT INTO `text` VALUES ('guide-project-description', 'es', 'Texto guía en el paso DESCRIPCIÓN del formulario de proyecto.');
INSERT INTO `text` VALUES ('guide-project-costs', 'es', 'Texto guía en el paso COSTES del formulario de proyecto.');
INSERT INTO `text` VALUES ('guide-project-rewards', 'es', 'Texto guía en el paso RETORNO del formulario de proyecto.');
INSERT INTO `text` VALUES ('guide-project-support', 'es', 'Texto guía en el paso COLABORACIONES del formulario de proyecto.');
INSERT INTO `text` VALUES ('guide-project-overview', 'es', 'Texto guía en el paso PREVISUALIZACIÓN del formulario de proyecto.');

INSERT INTO `text` VALUES ('guide-project-success-noerrors', 'es', 'Todos los campos obligatorios estan rellenados');
INSERT INTO `text` VALUES ('guide-project-success-minprogress', 'es', 'Ha llegado al porcentaje mínimo');
INSERT INTO `text` VALUES ('guide-project-success-okfinish', 'es', 'Puede enviar para valoración');
INSERT INTO `text` VALUES ('guide-project-error-mandatories', 'es', 'Faltan campos obligatorios');

INSERT INTO `text` VALUES ('error-register-user-exists', 'es', 'El usuario ya existe.');
INSERT INTO `text` VALUES ('error-register-username', 'es', 'El nombre de usuario usuario es obligatorio.');
INSERT INTO `text` VALUES ('error-register-email-exists', 'es', 'El dirección de correo ya corresponde a un usuario registrado.');
INSERT INTO `text` VALUES ('error-register-email', 'es', 'La dirección de correo es obligatoria.');
INSERT INTO `text` VALUES ('error-register-short-password', 'es', 'La contraseña debe contener un mínimo de 8 caracteres.');
INSERT INTO `text` VALUES ('error-register-pasword', 'es', 'La contraseña no puede estar vacía.');
INSERT INTO `text` VALUES ('error-register-email-confirm', 'es', 'La comprobación de email no coincide.');
INSERT INTO `text` VALUES ('error-register-password-confirm', 'es', 'La comprobación de contraseña no coincide.');
INSERT INTO `text` VALUES ('mandatory-project-field-contract-name', 'es', 'Es obligatorio poner el NOMBRE del responsable del proyecto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('mandatory-project-field-contract-surname', 'es', 'Es obligatorio poner los APELLIDOS del responsable del proyecto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('mandatory-project-field-contract-nif', 'es', 'Es obligatorio poner el NIF del responsable del proyecto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('validate-project-value contract-nif', 'es', 'El NIF no es correcto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('mandatory-project-field-contract-email', 'es', 'Es obligatorio poner el EMAIL del responsable del proyecto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('validate-project-value contract-email', 'es', 'El EMAIL no es correcto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('validate-project-value phone', 'es', 'El TELÉFONO no es correcto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('mandatory-project-field-residence', 'es', 'Es obligatorio poner el LUGAR DE RESIDENCIA del responsable del proyecto, paso 2: Datos personales.');
INSERT INTO `text` VALUES ('mandatory-project-field-name', 'es', 'Es obligatorio poner un NOMBRE al proyecto, paso 3: Descripción.');
INSERT INTO `text` VALUES ('mandatory-project-field-description', 'es', 'Es obligatorio poner una DESCRIPCIÓN al proyecto, paso 3: Descripción.');
INSERT INTO `text` VALUES ('validate-project-value description', 'es', 'La DESCRIPCIÓN del proyecto es demasiado corta, paso 3: Descripción.');
INSERT INTO `text` VALUES ('mandatory-project-field-category', 'es', 'Es obligatorio elegir una CATEGORIA para el proyecto, paso 3: Descripción.');
INSERT INTO `text` VALUES ('mandatory-project-field-media', 'es', 'Poner un vídeo para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-project-value-keywords', 'es', 'Indicar hasta 5 palabras clave del proyecto para mejorar la puntuación');
INSERT INTO `text` VALUES ('mandatory-project-field-location', 'es', 'Es obligatorio poner la LOCALIZACIÓN del proyecto, paso 3: Descripción.');
INSERT INTO `text` VALUES ('mandatory-project-costs', 'es', 'Debe desglosar en al menos DOS COSTES, paso 4 costes.');
INSERT INTO `text` VALUES ('validate-project-total-costs', 'es', 'El coste óptimo no puede superar en más de un 40% al coste mínimo. Revisar el DESGLOSE DE COSTES, paso 4 costes.');
INSERT INTO `text` VALUES ('mandatory-project-field-phone', 'es', 'El teléfono del responsable del proyecto es obligatorio');
INSERT INTO `text` VALUES ('mandatory-project-field-address', 'es', 'La dirección del responsable del proyecto es obligatoria');
INSERT INTO `text` VALUES ('mandatory-project-field-zipcode', 'es', 'El código postal del responsable del proyecto es obligatorio');
INSERT INTO `text` VALUES ('mandatory-project-field-country', 'es', 'El país del responsable del proyecto es obligatorio');
INSERT INTO `text` VALUES ('mandatory-project-field-image', 'es', 'Es obligatorio poner una imagen al proyecto');
INSERT INTO `text` VALUES ('mandatory-project-field-motivation', 'es', 'Es obligatorio explicar la motivación en la descripción del proyecto');
INSERT INTO `text` VALUES ('mandatory-project-field-about', 'es', 'Es obligatorio explicar qué es en la descripción del proyecto');
INSERT INTO `text` VALUES ('mandatory-project-field-goal', 'es', 'Es obligatorio explicar los objetivos en la descripción del proyecto');
INSERT INTO `text` VALUES ('mandatory-project-field-related', 'es', 'Es obligatorio explicar la experiencia relacionada y el equipo en la descripción del proyecto');
INSERT INTO `text` VALUES ('validate-user-field-name', 'es', 'Pon tu nombre completo para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-avatar', 'es', 'Pon una imagen de perfil para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-about', 'es', 'Cuenta algo sobre ti para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-interests', 'es', 'Selecciona algún interés para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-keywords', 'es', 'Indica hasta 5 palabras clave que te definan para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-contribution', 'es', 'Explica que podrias aportar en Goteo para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-webs', 'es', 'Pon tu página web para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-user-field-facebook', 'es', 'Pon tu cuenta de facebook para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-project-field-currently', 'es', 'Indicar el estado del proyecto para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-project-field-costs', 'es', 'Desglosar hasta 5 costes para mejorar la puntuación');
INSERT INTO `text` VALUES ('mandatory-cost-field-name', 'es', 'Es obligatorio ponerle un nombre al coste');
INSERT INTO `text` VALUES ('mandatory-cost-field-description', 'es', 'Es obligatorio poner alguna descripción');
INSERT INTO `text` VALUES ('validate-cost-field-dates', 'es', 'Indicar las fechas de inicio y final de este coste para mejorar la puntuación');
INSERT INTO `text` VALUES ('mandatory-project-field-resource', 'es', 'Es obligatorio especificar si cuentas con otros recursos');
INSERT INTO `text` VALUES ('validate-project-social_rewards', 'es', 'Indicar hasta 5 retornos colectivos para mejorar la puntuación');
INSERT INTO `text` VALUES ('validate-project-individual_rewards', 'es', 'Indicar hasta 5 recompensas individuales para mejorar la puntuación');
INSERT INTO `text` VALUES ('mandatory-social_reward-field-name', 'es', 'Es obligatorio poner el retorno');
INSERT INTO `text` VALUES ('mandatory-social_reward-field-description', 'es', 'Es obligatorio poner alguna descripción al retorno');
INSERT INTO `text` VALUES ('validate-social_reward-license', 'es', 'Indicar una licencia para mejorar la puntuación');
INSERT INTO `text` VALUES ('mandatory-individual_reward-field-name', 'es', 'Es obligatorio poner la recompensa');
INSERT INTO `text` VALUES ('mandatory-individual_reward-field-description', 'es', 'Es obligatorio poner alguna descripción');
INSERT INTO `text` VALUES ('mandatory-individual_reward-field-amount', 'es', 'Es obligatorio indicar el importe que otorga la recompensa');
INSERT INTO `text` VALUES ('mandatory-support-field-name', 'es', 'Es obligatorio ponerle un nombre a la colaboración');
INSERT INTO `text` VALUES ('mandatory-support-field-description', 'es', 'Es obligatorio poner alguna descripción');

INSERT INTO `text` VALUES ('tooltip-user-user', 'es', 'Consejo para rellenar el nombre de usuario para login');
INSERT INTO `text` VALUES ('tooltip-user-email', 'es', 'Consejo para rellenar el email de registro de usuario');
INSERT INTO `text` VALUES ('tooltip-user-name', 'es', 'Consejo para rellenar el nombre completo del usuario');
INSERT INTO `text` VALUES ('tooltip-user-image', 'es', 'Consejo para rellenar la imagen del usuario');
INSERT INTO `text` VALUES ('tooltip-user-about', 'es', 'Consejo para rellenar el cuéntanos algo sobre tí');
INSERT INTO `text` VALUES ('tooltip-user-interests', 'es', 'Consejo para seleccionar tus intereses');
INSERT INTO `text` VALUES ('tooltip-user-keywords', 'es', 'Consejo para rellenar tus palabras clave');
INSERT INTO `text` VALUES ('tooltip-user-contribution', 'es', 'Consejo para rellenar el qué podrías aportar en goteo');
INSERT INTO `text` VALUES ('tooltip-user-blog', 'es', 'Consejo para rellenar la web');
INSERT INTO `text` VALUES ('tooltip-user-twitter', 'es', 'Consejo para rellenar el twitter');
INSERT INTO `text` VALUES ('tooltip-user-facebook', 'es', 'Consejo para rellenar el facebook');
INSERT INTO `text` VALUES ('tooltip-user-linkedin', 'es', 'Consejo para rellenar el linkedin');

INSERT INTO `text` VALUES ('tooltip-project-contract_name', 'es', 'Consejo para rellenar el nombre del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-contract_surname', 'es', 'Consejo para rellenar el apellido del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-contract_nif', 'es', 'Consejo para rellenar el nif del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-contract_email', 'es', 'Consejo para rellenar el email del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-phone', 'es', 'Consejo para rellenar el teléfono del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-address', 'es', 'Consejo para rellenar el address del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-zipcode', 'es', 'Consejo para rellenar el zipcode del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-location', 'es', 'Consejo para rellenar el lugar de residencia del responsable del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-country', 'es', 'Consejo para rellenar el país del responsable del proyecto');

INSERT INTO `text` VALUES ('tooltip-project-name', 'es', 'Consejo para rellenar el nombre del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-image', 'es', 'Consejo para rellenar la imagen del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-description', 'es', 'Consejo para rellenar la descripción del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-motivation', 'es', 'Consejo para rellenar el campo motivación');
INSERT INTO `text` VALUES ('tooltip-project-about', 'es', 'Consejo para rellenar el campo qué es');
INSERT INTO `text` VALUES ('tooltip-project-goal', 'es', 'Consejo para rellenar el campo objetivos');
INSERT INTO `text` VALUES ('tooltip-project-related', 'es', 'Consejo para rellenar el campo experiencia relacionada y equipo');
INSERT INTO `text` VALUES ('tooltip-project-category', 'es', 'Consejo para seleccionar la categoría del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-keywords', 'es', 'Consejo para rellenar las palabras clave del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-media', 'es', 'Consejo para rellenar el media del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-currently', 'es', 'Consejo para rellenar el estado de desarrollo del proyecto');
INSERT INTO `text` VALUES ('tooltip-project-project_location', 'es', 'Consejo para rellenar la localización del proyecto');

INSERT INTO `text` VALUES ('tooltip-project-ncost', 'es', 'Consejo para rellenar un nuevo desglose de costes');
INSERT INTO `text` VALUES ('tooltip-project-cost', 'es', 'Consejo para editar desgloses existentes');
INSERT INTO `text` VALUES ('tooltip-project-resource', 'es', 'Consejo para rellenar el campo Cuenta con otros recursos?');

INSERT INTO `text` VALUES ('tooltip-project-nsocial_reward', 'es', 'Consejo para rellenar un nuevo retorno colectivo');
INSERT INTO `text` VALUES ('tooltip-project-social_reward', 'es', 'Consejo para editar retornos colectivos existentes');
INSERT INTO `text` VALUES ('tooltip-project-nindividual_reward', 'es', 'Consejo para rellenar un nuevo retorno individual');
INSERT INTO `text` VALUES ('tooltip-project-individual_reward', 'es', 'Consejo para editar retornos individuales existentes');

INSERT INTO `text` VALUES ('tooltip-project-nsupport', 'es', 'Consejo para rellenar una nueva colaboración');
INSERT INTO `text` VALUES ('tooltip-project-support', 'es', 'Consejo para editar colaboraciones existentes');

-- INSERT INTO `text` VALUES ('------- id max lenght --------------------------', 'es', '');
