CREATE TABLE `task` (
`id` SERIAL NOT NULL ,
`node` VARCHAR( 50 ) NOT NULL ,
`text` TEXT NOT NULL ,
`url` TINYTEXT NULL DEFAULT NULL ,
`done` VARCHAR( 50 ) NULL DEFAULT NULL ,
`datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY ( `id` )
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Tareas pendientes de admin';


-- engine
ALTER TABLE `task` ENGINE = InnoDB;


-- constrains
ALTER TABLE `task` ADD FOREIGN KEY (`node`) REFERENCES `node`(`id`) ON UPDATE CASCADE ON DELETE CASCADE;
