name: "[CI] Test"

on:
  push:
    branches:
      - main
      - live
  pull_request:

env:
  GOTEO_CONFIG_FILE: config/github-settings.yml

jobs:
  test-report:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.4' ]

    services:
      mysql:
        image: mariadb:10.2
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: goteo
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: goteo
          MYSQL_PASSWORD: goteo
          MYSQL_ROOT_PASSWORD: goteo
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Install compile gems
        run: |
          sudo gem install sass -v 3.4.23
          sudo gem install compass

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install NPM packages
        run: |
          sudo npm install grunt -g --prefix=/usr/local
          npm install

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, xml

      - name: Run Composer Install
        run: composer install --no-interaction

      - name: Run migrations
        run: bin/console migrate install

      - name: Grunt compile assets
        run: grunt build:dist

      - name: Run tests
        run: ./run-tests.sh -t config/github-settings.yml tests/
