<?php $bodyClass = 'home'; include 'view/prologue.html.php' ?>

        <?php include 'view/header.html.php' ?>

        <div id="main">
        <?php if (isset($_GET['lipsum'])): ?>
        <p> 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis hendrerit nisl at dapibus. Maecenas vulputate sodales luctus. Vestibulum rhoncus viverra metus, vel tincidunt massa imperdiet rutrum. Aenean gravida neque sed sapien vulputate viverra. Etiam mauris leo, dictum vitae consequat scelerisque, dignissim vel ante. Vivamus ac nulla quis nunc pulvinar accumsan. Aenean non lorem et tortor laoreet posuere et vitae nulla. Donec non lacus eros. Aenean fringilla odio a nibh porta accumsan. Cras lobortis porttitor fermentum. Sed tempus justo sit amet purus faucibus laoreet molestie est semper. Vivamus elit neque, rhoncus vel hendrerit aliquet, imperdiet et diam. Maecenas posuere magna nec neque ornare sagittis.
</p> 
<p> 
Fusce fringilla convallis nisi, vitae consequat mauris tristique a. Aenean et odio ac nulla bibendum ornare. Integer id elit a lorem mattis adipiscing. Aliquam bibendum augue in nisi facilisis venenatis. Integer eget magna et diam elementum auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus pulvinar pellentesque turpis non condimentum. Cras a odio diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor nisl sed orci varius venenatis lacinia tellus mattis. Fusce vel urna tristique augue feugiat condimentum eget a ligula.
</p> 
<p> 
Phasellus est risus, cursus in posuere in, commodo id felis. Mauris non sem turpis. Maecenas urna leo, elementum ac placerat vel, tempus sed leo. Etiam quis hendrerit metus. Nam tincidunt nisl nec nibh facilisis congue. Maecenas egestas semper ultrices. Praesent luctus, velit vel suscipit blandit, quam lectus faucibus augue, a cursus lorem ligula non urna. Sed porta egestas egestas. Curabitur nisi justo, rhoncus ut lobortis nec, dignissim sed leo. Praesent tellus quam, malesuada eget lacinia ac, venenatis scelerisque lacus. Nam sed enim in augue varius lobortis non et elit. In hac habitasse platea dictumst. Duis sit amet odio risus. Mauris nec quam non mi pretium pharetra vestibulum eget eros. Quisque tincidunt, nulla ut euismod elementum, tortor ligula tincidunt ligula, ut vulputate urna nulla ac dolor.
</p> 
<p> 
Suspendisse potenti. Donec at faucibus mi. Aliquam erat volutpat. Nullam ullamcorper pharetra condimentum. Maecenas consequat augue id felis placerat pellentesque. Praesent elementum luctus mattis. Cras nibh sapien, tincidunt a suscipit eu, varius a ligula. Vivamus purus justo, faucibus auctor semper vitae, tincidunt non turpis. Cras lorem lectus, aliquet eu faucibus eu, pellentesque quis magna. Sed lobortis pharetra tortor sed fringilla.
</p> 
<p> 
Cras aliquam cursus imperdiet. Proin nisl ligula, scelerisque ac egestas eu, imperdiet et nulla. Nulla ac mollis libero. Curabitur suscipit, nisl et adipiscing aliquet, nisl enim pretium est, nec accumsan dui eros ut diam. Vivamus elementum, ligula a varius gravida, nisl turpis luctus neque, in interdum lectus nibh nec est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in arcu sit amet sapien suscipit vulputate. Aliquam sollicitudin aliquam magna, ut fringilla turpis varius sit amet. Nullam porta scelerisque orci, id fermentum dui semper facilisis. Mauris egestas libero non enim lobortis consequat. Fusce vestibulum ultricies hendrerit. Morbi eu pulvinar mi. Curabitur ac adipiscing arcu. Nunc porttitor sollicitudin erat, eu feugiat dolor porttitor vel. Vestibulum fermentum nunc vitae nisi aliquam egestas. Sed auctor justo ac velit rhoncus id varius urna placerat. Pellentesque vitae lobortis dui. Nunc quis magna nibh, at condimentum risus.
</p> 
<p> 
Aliquam non ipsum est. Aliquam et convallis ligula. Quisque eget ipsum et erat porttitor mollis. Fusce rhoncus, nulla vel mollis laoreet, mauris felis porttitor metus, ut cursus tortor justo sed nibh. Quisque pretium felis in lorem hendrerit posuere. Cras viverra faucibus dolor a scelerisque. In elit mi, vulputate non scelerisque tristique, convallis non neque. Donec faucibus leo non ipsum feugiat sed eleifend orci laoreet. Quisque blandit dolor vel erat vulputate eget porttitor lorem vestibulum. Praesent sodales eros non quam aliquet scelerisque. Etiam quis pharetra odio. Quisque vehicula ornare risus, eu sodales tellus lobortis a. Pellentesque porttitor pulvinar rutrum. Aliquam erat volutpat. Aenean vel arcu sem. Ut at tortor turpis, at porta purus. Vivamus et eros suscipit tortor sagittis congue nec eu erat. Pellentesque non metus eget nulla convallis faucibus a at nisi. Suspendisse potenti. Morbi porttitor condimentum orci, in ultrices lectus ullamcorper sit amet.
</p> 
<p> 
Donec lacus dui, molestie eget fermentum eu, interdum ac nunc. Sed ut urna magna. Morbi at eros interdum ipsum mollis mollis. Mauris eu turpis augue. Nunc sit amet placerat odio. Maecenas orci justo, mollis sed porttitor vitae, commodo ut magna. Integer ligula dui, ultricies eget auctor nec, pharetra quis purus. Cras adipiscing, odio sed rutrum porttitor, lectus eros rhoncus tortor, vel elementum nibh nunc accumsan turpis. Nam mi tellus, congue id laoreet in, elementum eu lorem. Ut vel ligula sit amet enim dictum pellentesque id id lacus. Cras faucibus adipiscing sagittis. Proin dapibus placerat orci, in euismod eros porttitor non. Phasellus dui nisi, consectetur a rhoncus non, cursus a magna. Aenean sed metus risus, in consequat felis. Ut et massa sed nisi congue adipiscing ut id nisi. Phasellus varius congue urna, in condimentum diam cursus et. Nunc aliquet, ligula vel consequat sodales, lorem metus lacinia velit, vitae blandit lacus nisi at felis.
</p> 
<p> 
Mauris sollicitudin facilisis lobortis. Proin non hendrerit nisl. Sed sed ullamcorper leo. Nulla in leo eu ante scelerisque placerat. Mauris condimentum, odio nec ultricies commodo, orci nibh bibendum erat, commodo convallis massa nunc in libero. Nullam semper leo in risus venenatis rhoncus. Pellentesque consectetur vestibulum facilisis. Curabitur lorem augue, rutrum nec mollis id, euismod vel massa. Phasellus eget rutrum lacus. Integer sodales, lorem a luctus porttitor, orci elit suscipit elit, id sagittis leo diam interdum est. Aliquam sed purus dolor, eget mollis risus. Duis interdum tincidunt orci, in suscipit dolor volutpat egestas. Fusce non interdum ante. Aliquam facilisis ante viverra libero suscipit vitae ultricies diam consectetur. Morbi ornare purus sit amet lorem vestibulum vestibulum. Etiam nec tempus arcu.
</p> 
<p> 
Vivamus dignissim, justo at consectetur ultricies, nulla odio malesuada sem, et dictum urna nulla vitae elit. Pellentesque a massa sit amet lorem feugiat consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed mauris velit, volutpat mollis lobortis id, malesuada vitae tellus. In non turpis ac risus rhoncus facilisis quis vel est. Praesent arcu orci, dignissim sit amet iaculis eget, suscipit et libero. Donec a magna lacus. Quisque quis metus non lectus iaculis bibendum nec id dui. Nunc dignissim eros eget purus malesuada feugiat. Etiam laoreet, diam porta mollis pharetra, velit purus gravida justo, vel gravida lacus leo et neque. Suspendisse hendrerit, magna eu molestie malesuada, felis nisi porttitor dolor, eu feugiat sem odio consequat ante.
</p> 
<p> 
Curabitur vitae arcu vitae nibh lacinia convallis. Donec volutpat luctus nulla, eu semper mauris scelerisque ut. Donec consequat molestie diam ut tristique. Mauris tellus neque, suscipit sed suscipit sit amet, bibendum sed risus. Vivamus imperdiet nunc et tellus placerat scelerisque fringilla leo cursus. Vestibulum metus turpis, faucibus vitae convallis varius, commodo in libero. Nunc vitae urna dolor. Fusce sit amet tortor non risus interdum auctor. Quisque accumsan suscipit tempus. Duis eu tellus dui, eu vulputate eros.
</p> 
<p> 
Proin luctus massa vehicula sem mollis vehicula vestibulum velit interdum. Cras gravida justo ut erat vulputate commodo. Curabitur scelerisque laoreet erat, eget tincidunt turpis consectetur at. In ultricies dignissim arcu in lobortis. Sed eu ante sem. Duis tellus tortor, convallis ac convallis in, blandit in tellus. Sed porttitor, nisl at porta tincidunt, mi sem ullamcorper ligula, vitae fringilla lectus velit ac nisi. Sed non nunc sit amet neque consequat viverra. Mauris nec diam dignissim magna gravida cursus. Cras luctus dui tristique turpis posuere molestie. Sed quis molestie risus.
</p> 
<p> 
Duis risus diam, vestibulum porttitor feugiat eu, ullamcorper et erat. Pellentesque sit amet magna quam, condimentum porttitor dolor. Fusce pellentesque luctus tincidunt. Donec rhoncus lacinia posuere. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec mi sapien, tincidunt non porta vel, cursus lobortis sapien. Nam non justo felis, a dignissim enim. Proin vel nunc mi. Morbi augue est, facilisis et interdum sed, laoreet interdum est. Vestibulum quis lorem massa. Quisque eget malesuada neque. Integer eget eros ut dolor scelerisque tempus. Etiam tristique pellentesque nunc eu hendrerit. Etiam dapibus leo id dolor scelerisque laoreet. Etiam et accumsan dolor.
</p> 
<p> 
Mauris non odio turpis. Quisque dolor elit, cursus id euismod sed, blandit a neque. Mauris iaculis ullamcorper felis, vitae vestibulum metus dignissim non. Vivamus aliquam placerat consectetur. Vivamus sit amet lorem felis. In dolor sem, pretium vel ornare at, egestas quis turpis. Quisque sed euismod nunc. Quisque tristique, orci lobortis consequat accumsan, elit turpis eleifend est, non fermentum nisl ante in tellus. Donec sed libero sapien, ac aliquet sem. Praesent faucibus interdum erat. Pellentesque vel odio erat, ut sollicitudin quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent ultrices, nunc vel dictum bibendum, erat neque hendrerit felis, in eleifend arcu diam et massa. Praesent sit amet mi quis leo eleifend porttitor aliquet nec mi.
</p> 
<p> 
Curabitur eu metus massa. Duis id ipsum nec erat scelerisque tempus. Suspendisse accumsan imperdiet metus non facilisis. In ultrices euismod libero, in porttitor lorem dictum id. Nullam a erat massa, at consequat urna. Ut nisl augue, dictum non euismod ut, consequat ac risus. Donec porttitor malesuada massa, eu elementum mauris scelerisque nec. Etiam tempor luctus sapien, a lacinia massa pharetra ac. Ut eleifend pharetra est, vel interdum turpis accumsan ac. Nulla fermentum ultricies quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
</p> 
<p> 
Duis ut dolor a enim lobortis blandit. Suspendisse lacinia dolor ac dolor bibendum pharetra venenatis magna vestibulum. Phasellus molestie ullamcorper massa. Quisque nec pellentesque enim. Donec consequat pellentesque est, vitae sollicitudin leo sodales at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et justo nulla, quis convallis ante. Morbi egestas fermentum quam, sit amet luctus velit vestibulum ac. Ut rutrum tempus pharetra. In viverra rutrum justo, ac ornare urna auctor vel. Integer urna lorem, rhoncus sit amet tincidunt a, sollicitudin vel elit. Sed nibh ante, sollicitudin a lacinia ut, faucibus ut ante. Morbi in augue metus, auctor lobortis risus. Suspendisse potenti. In hac habitasse platea dictumst.
</p> 
<p> 
Curabitur tempus nisl ultricies arcu aliquam in feugiat arcu sodales. Aliquam venenatis feugiat sem, non auctor risus porta vel. Sed non augue sit amet leo tempor lobortis. Cras nec mi ligula, vel tincidunt arcu. Praesent faucibus tincidunt magna et accumsan. Etiam egestas lacinia elit, eget aliquam leo fermentum sit amet. Ut pellentesque nisi ac nisi pellentesque mattis. Nunc in eros sit amet nibh dapibus feugiat. Fusce vehicula hendrerit ornare. Fusce lacinia, lacus quis porta tincidunt, diam augue porttitor ipsum, quis aliquet purus neque ac nulla. Nulla facilisi. Ut gravida, augue id suscipit hendrerit, leo orci ultrices dolor, sit amet lacinia leo ligula quis nisi.
</p> 
<p> 
In nibh odio, tincidunt non iaculis nec, molestie ut erat. Nullam adipiscing sapien nec magna rhoncus sit amet gravida nisi lobortis. Sed quis libero eget turpis laoreet fringilla vitae et nulla. Morbi vitae massa dolor. Suspendisse euismod risus quis eros euismod consectetur. Morbi sed arcu et lectus venenatis aliquam quis vitae est. Ut sed eros velit. Sed facilisis dui ac dolor auctor fringilla. Pellentesque vitae lacus ut arcu ultricies mollis. Mauris et mauris porta metus dictum auctor sed sed lacus. Ut nisi odio, porta vitae fermentum at, mattis ut sem.
</p> 
<p> 
Phasellus rutrum justo ac augue varius et accumsan leo fringilla. Proin congue dolor ac leo cursus feugiat. Nulla facilisi. Curabitur ac lectus vel felis commodo porttitor. Praesent semper venenatis imperdiet. Vestibulum eros mi, dictum nec consectetur at, fringilla eu risus. Curabitur vel odio id quam posuere ornare. Vivamus ut metus nec mi laoreet accumsan hendrerit in massa. Quisque et lectus urna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean aliquet lacus id tellus sagittis dignissim. Mauris ornare dui in dui sollicitudin elementum. Suspendisse potenti. In at ante non orci molestie sollicitudin a facilisis lacus. Praesent tempor luctus purus at blandit. Praesent cursus, sapien ut auctor molestie, erat orci rutrum nibh, vitae rhoncus turpis leo iaculis leo. Vestibulum elit metus, rhoncus vitae iaculis sit amet, dapibus sit amet eros. Mauris semper mollis eros, sit amet semper justo rhoncus rhoncus. Nullam hendrerit sodales dictum.
</p> 
<p> 
Integer sit amet felis felis. Pellentesque interdum tristique turpis, ut imperdiet odio lobortis non. Mauris bibendum gravida sollicitudin. Aenean velit tellus, tincidunt a blandit in, dignissim non nisi. In faucibus auctor lobortis. Sed volutpat sollicitudin leo, sit amet cursus sem placerat non. Proin at purus eros. In pretium dictum euismod. Mauris fermentum, orci at aliquam imperdiet, neque magna iaculis elit, et mattis nibh urna at turpis. Donec tincidunt placerat faucibus. Nam sed nisi eros, non ornare tellus. Curabitur et adipiscing neque. Donec et justo ut quam euismod convallis id consequat lorem. Proin gravida sodales rutrum. Donec interdum commodo mollis. Aliquam erat volutpat. Mauris eleifend congue sapien sit amet hendrerit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam elementum ligula orci.
</p> 
<p> 
Sed rutrum facilisis sodales. Phasellus dapibus lacus varius ante tincidunt consequat vel vitae elit. Donec sit amet augue eget arcu ornare molestie. Pellentesque laoreet, velit ut euismod varius, turpis metus ornare mauris, quis ultricies ipsum urna in justo. Proin ac elit eget lacus ultrices cursus ut sit amet lorem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ligula augue, tincidunt sit amet convallis vitae, lacinia adipiscing ante. Mauris ultricies hendrerit sapien ut egestas. Suspendisse mi lectus, cursus non ultricies vitae, aliquet vel nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque eu elementum nisl. Morbi condimentum cursus mauris. Aliquam adipiscing, felis sit amet scelerisque blandit, nunc justo tempus purus, in blandit ante enim in massa. Maecenas vestibulum justo ac justo tincidunt viverra. Aliquam erat volutpat. Donec sollicitudin, nulla tincidunt ultricies pellentesque, leo ligula sagittis odio, non aliquet sem dolor eu velit. Suspendisse nec purus eget urna tincidunt mattis. Etiam vitae sapien nulla.
</p>
<?php endif ?>
        </div>        

        <?php include 'view/footer.html.php' ?>
    
<?php include 'view/epilogue.html.php' ?>